### ISSUE TITLE
Unable to resolve ReactComponentWithPureRenderMixin

### ISSUE THREAD

**Issue by 759325100** [react-community/react-navigation#1040]
my package.json
<code>
{
"name": "AwesomeProject",  
"version": "0.0.1",  
"private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.0.0-alpha.6",
    "react-native": "0.43.3",
    "react-native-button-component": "^0.1.16",
    "react-native-check-box": "^1.0.4",
    "react-native-easy-toast": "^1.0.5",
    "react-navigation": "git+https://github.com/react-community/react-navigation.git"
  },
  "devDependencies": {
    "babel-jest": "19.0.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "19.0.2",
    "react-test-renderer": "16.0.0-alpha.6"
  },
  "jest": {
    "preset": "react-native"
  }
}
</code>

**Comment by 759325100** [comment]
i try 923 and 906
The problem still exists

**Comment by skyworld** [comment]
![image](https://cloud.githubusercontent.com/assets/4318550/25033894/b29b5b1a-2114-11e7-8147-3d9b184f0bf9.png)
I also have this problem, and don't know how to solve it.
This error happens when I upgrade my react-native to version 0.43.0

**Comment by grabbou** [comment]
It should be fixed in master where our `Header` uses `PureComponent` instead.

**Comment by 759325100** [comment]
I do not quite understand
I try to update to the latest version
The problem still exists

**Comment by 759325100** [comment]
I tried to remove <code> Header.js </code>  
<code> import ReactComponentWithPureRenderMixin from 'react / lib / ReactComponentWithPureRenderMixin'; </code>
The problem is solved
Thanks again

**Comment by nonameolsson** [comment]
You shouldn't remove code from those files. 

Try to remove `node_modules` and then run `npm install` to get the latest code.

If you still have your problem try with this:
`rm -rf $TMPDIR/react-* && watchman watch-del-all && rm -rf ios/build/ModuleCache/* && rm -rf node_modules/ && npm cache clean && npm install`

**Comment by valerybugakov** [comment]
@grabbou could you release fixed version to NPM, please? Facing the same issue.

**Comment by grabbou** [comment]
We will release a new version soon, for now you can try master.

**Comment by valerybugakov** [comment]
@grabbou thanks!

**Comment by runeogod** [comment]
@nonameolsson Your solution fixed my issue. Thanks

**Comment by SeanChenU** [comment]
+1
