### ISSUE TITLE
How to reset the navigation stack without animation?

### ISSUE THREAD

**Issue by diegorodriguesvieira** [react-community/react-navigation#1493]
How can I reset the navigation stack without this animation?

![](https://media.giphy.com/media/xUA7b9GVn128oTGLle/giphy.gif)

My code:
```
resetTabAction = NavigationActions.navigate({
  routeName: 'Dashboard',
  action: NavigationActions.reset({
    index: 0,
    actions: [NavigationActions.navigate({ routeName: 'DashboardInitial' })],
  }),
});
props.navigation.dispatch(resetTabAction);
```

**Comment by aqnaruto** [comment]
and how to set  stack navigation with go-back gesture?

**Comment by JuiceCrawl** [comment]
I'm having the same problem with animations when I reset or navigate backwards more than 1 screen. Here's the [StackOverflow question](http://stackoverflow.com/questions/43946437/react-navigation-navigate-back-to-root-using-navigationactions-reset-goback-an)

**Comment by davidysong** [comment]
I have the same issue also. I am wondering if using a custom Transitioner would allow resetting the stack without any animations: https://reactnavigation.org/docs/views/transitioner

**Comment by aqnaruto** [comment]
@diegorodriguesvieira hey, you need not to jump to another page, just use header null , and setstate in one page render different component

**Comment by LaurensLang** [comment]
@diegorodriguesvieira i don't understand?

**Comment by diegorodriguesvieira** [comment]
@aqnaruto but if I just navigate to a page without a header, I'll still have the navigation stack with the items because it has not been reset, can I have performance issues with that?

**Comment by diegorodriguesvieira** [comment]
@LaurensLang I need to reset to the first navigation page inside the tab, however without seeing the animations for each card in the stack

**Comment by diegorodriguesvieira** [comment]
@davidysong I will try, thanks

**Comment by itswaze** [comment]
+1 anyone with a solution?

**Comment by sckoh** [comment]
+1

**Comment by lyubo** [comment]
+1

**Comment by mnkang89** [comment]
+1

**Comment by MSchmidt** [comment]
@diegorodriguesvieira did you figure this out yet? What you are trying to accomplish is basically default iOS behaviour and should work out of the box ideally.

**Comment by faceyspacey** [comment]
Here's a concise proposal that will fix this in many other issues:

https://github.com/react-community/react-navigation/issues/1663

**Comment by binzailani3136** [comment]
I've really similar issue.
My navigation structure is like below

TabNavigator
---Tab1(StackNavigator)
--------Screen1
----------Screen2
---Tab2
---Tab3

The problem is - when first land on Tab1, it shows Screen1 and I can navigate to Screen2.
And then I go to Tab2 and I go back Tab1 again and reset the Tab1's StackNavigator to show Screen1(First page of Tab1) because Tab1's current page is Screen2.
Reset works but when I am doing reset, it shows transition animation of back transition Screen2->Screen1
I really want to remove this back transition animation when resetting Tab1's StackNavigator.
Is there any workaround of this issue?

I've spent so much time to solve this issue and googled a lot.
But no appropriate answers about this issue.
Some one answered that we can use `transitionConfig` option but if we remove animation by this option, the animation of navigate action also removed.
Such as Screen1->Screen2 animation also removed because `transitionConfig` is set on StacNavigator of Tab1 and this config removes all animation of Tab1's StackNavigator.

I want to show animation when navigating and only want to remove animation when resetting.
Thanks

**Comment by cccRaim** [comment]
+1
When I want to backward more than 1 screen, the animation is "5-4-3-2-1", but I just want "5-1"

**Comment by jamesone** [comment]
@diegorodriguesvieira Did you find a workaround for this?

**Comment by diegorodriguesvieira** [comment]
Hello @jamesone, unfortunately I have not found any workaround yet...

**Comment by NSshentu** [comment]
@diegorodriguesvieira @jamesone 
i also get the same problem. So if you have any workaround pelase tell me .

**Comment by NSshentu** [comment]
@cccRaim 中间页面的闪屏怎么去掉，，，你有方法吗？

**Comment by rajsuvariya** [comment]
Has anyone found any solution for this issue?

**Comment by NSshentu** [comment]
@rajsuvariya yeah~ I change some project code then it work fine.  You can check this https://github.com/gorokhovich/react-navigation/commit/30e6d0cc73406e7697f5b846a3a7c6a1ddca9862

**Comment by rajsuvariya** [comment]
@NSshentu sorry I am not able to understand anything from the link. Can you provide code for removing animations?

**Comment by NSshentu** [comment]
@rajsuvariya 
+
 +  // work around for flashing scenes
 +  let k = null;
 +  let v = null;
 +  staleScenes.forEach(scene => {
 +    let {key} = scene;
 +    k = key;
 +    v = scene;
 +  });
 +
 +  newStaleScenes = k && v ? new Map([[k, v]]) : new Map();
 +  newStaleScenes.forEach(mergeScene);
 +  // staleScenes.forEach(mergeScene);
 +  // work around end
  
use the + code replace the function:
 staleScenes.forEach(mergeScene);
in src/views/ScenesReducer.js file

**Comment by rajsuvariya** [comment]
@NSshentu Thanks it solved the issue

**Comment by acahir** [comment]
Same issue. From the reactions on this issue, it sounds like most would assume a single transition animation on a reset should be the default.

@NSshentu are you going to submit a PR?

**Comment by NSshentu** [comment]
@acahir   i won't submit it, they may will fix it soon. in fact, there are lots of issues about this problem. 
And there are some problem about present a single page in modal way...and some other reasons, my team use navigator. In my opinion, the API really not so kindly.

**Comment by tibazi** [comment]
+1

**Comment by guoliang1206** [comment]
so, up to now, does the react-navigation team fixed this issue? And there has a stable version could be use?

**Comment by spencercarli** [comment]
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by freemanon** [comment]
Correct me if I'm wrong, but I would think that not being able to reset the navigation stack properly (without 5 screens flying backwards) is a problem. Unless there's already another issue for it.

I think the title of this issue should be renamed. It looks like someone's stackoverflow question but it's a legit problem

**Comment by dsimmons** [comment]
Just wanted to second the above -- while the original issue creation may have been phrased as a question, this is a bug in my opinion.

I can only speak for myself, but I +1'ed (thumbs'ed-up) this issue having encountered it myself and done some diligence in the way of seeing if anyone else had encountered it before filing a new issue. I'd expect that most all of the other thumbs-ups on this thread are from people in the same boat.

I'm sure @diegorodriguesvieira would be willing to rephrase the issue title to make it more clear that it's a bug (or at least undesirable behavior).

cc @spencercarli, because I'm sure you're getting a bazillion non-pertinent notifications having recently dealt with so many issue threads.

**Comment by alexwasner** [comment]
I find it quite absurd that this was closed as "a question." This is a bug that is the sole reason I switched to a different navigation stack and is preventing multiple apps in my organization from moving forward using React Navigation. @spencercarli please re-open this

**Comment by brentvatne** [comment]
@alexwasner - fair point, let's try to be a bit more polite to each other though :) Spencer is doing his best to manage this massive number of issues! If you'd like to submit a solution for this it would be great

**Comment by alexwasner** [comment]
@brentvatne Wasn't trying to be rude, so sorry if it came across that way. I appreciate the work being done on this, but it just seems the project grew too large to manage and the quickest way forward was to remove anything that looked like a question, regardless of valid bugs those questions posed.

**Comment by j3rin** [comment]
Does anyone have a solution to this problem?

**Comment by rpopovici** [comment]
@diegorodriguesvieira  you have to do this the other way around by dispatching reset first with a key and secondary action to be navigate.

Something like this:
`resetTabAction = NavigationActions.reset({
    key: 'navigator_key_to_reset',
    actions: [NavigationActions.navigate({ routeName: 'DashboardInitial' })],
  });
props.navigation.dispatch(resetTabAction);`

**Comment by rajatbeck** [comment]
Still waiting for a fix for this.
PS: @diegorodriguesvieira How do you get `navigator_key_to_reset` for the route? Can it be defined in router?

**Comment by rpopovici** [comment]
@rajatbeck  each navigator assigns a key for a route. Tab Navigator will use the route's name as key and StackNavigator uses a random key in order to allow you to push same route multiple times. You can get your route key from this.props.navigation.state.key. Currently, there's a bug in StackRouter which is not allowing the TabRouter to reset inactive route. There is a PR for this #2292 and more info here #723

**Comment by celso-henrique** [comment]
any news?

**Comment by vonovak** [comment]
while my code does not do a reset, it does `goBack`:

```
function goBackToRouteWithName(routeName: string) {
  if (!_container) return;
  const route = getRouteWithName(_container.state.nav, routeName);
  route && _container.dispatch(NavigationActions.back({ key: route.key }));
}

function getRouteWithName(navigationState, name: string) {
  if (!navigationState) {
    return null;
  }
  const route = navigationState.routes[navigationState.index];
  // dive into nested navigators
  if (route.routes) {
    // NOTE FIXME there must be a bug in react-navigation, normally you'd use find() and return that one
    const index = route.routes.findIndex(r => r.routeName === name);
    if (index > -1) return route.routes[index + 1];
    return getRouteWithName(route, name);
  }
}

```

I use this is a NavigatorService as described in #1439

**Comment by younanjo** [comment]
anyone has had any luck with this? Seems like a genuine problem, I got into this issue right from the get go! 😞  are there any workaround you guys are using to get around this?

**Comment by guoliang1206** [comment]
@yananjo no solution to solve this issue perfectly

**Comment by haxxpop** [comment]
+1

**Comment by etaiklein** [comment]
+1

**Comment by rishabhbhatia** [comment]
+1

**Comment by rishabhbhatia** [comment]
@NSshentu your code works, but it gives black screen for a second. any solution?

**Comment by evollu** [comment]
My temporary solution is creating a custom action `Navigation/ROOT` and do a init followed by reset. In that case there is no animation.

and my reducer looks like 
```
export const reducer = (state, action: any = {}) => {
  let newState;
  if (action.type === 'Navigation/ROOT') {
    newState = AppNavigator.router.getStateForAction(NavigationActions.reset({
      index: 0,
      actions: [
        NavigationActions.navigate({ routeName: action.routeName })
      ]
    }), AppNavigator.router.getStateForAction(NavigationActions.init()));
  } else {
    newState = AppNavigator.router.getStateForAction(action, state);
  }
  return newState || state;
}
```

**Comment by etaiklein** [comment]
@evollu this ended up overwriting my Home routename (though it may be more related to my setup). 

This solution worked for my personal setup:
```
export const reducer = (state, action: any = {}) => {
  let newState;
  if (action.type === 'Navigation/ROOT') {
    // fully reset routes to initial state
    newState = AppNavigator.router.getStateForAction(NavigationActions.init());
    // put me back on my last tab
    newState.routes[0].index = TabHomeRoutes.indexOf(action.routeName);
  } else {
    newState = AppNavigator.router.getStateForAction(resultingAction, state);
  }
  return newState || state;
}
```

**Comment by W0LFMAN** [comment]
Found solution!
Add to root Scene - transactionConfig like this. This will control your animation.
As we see, I set the duration for animations by "Actions.lastActionType" that writes in reducer of Router. 
REMEMBER that transitionConfig on root Scene applies for all routes.
But you can change animations for scenes dynamically with "screenInterpolator" function.
In sceneProps argument, you receive all needed information about handled scenes.
For full info read "react-navigation" docs.
```javascript
<Scene
        key="root"
        transitionConfig={function(){
          return {
            transitionSpec: {
              duration: Actions.lastActionType === 'Navigation/RESET' ? 0 : 300
            },
            screenInterpolator: sceneProps => {
              const { layout, position, scene, navigation, router } = sceneProps;
              const { index, route: { routeName } } = scene;
              // const { transitionConfig } = sceneProps.router.getScreenOptions({ state: navigation.state.routes[navigation.state.index] });
              const translateX = position.interpolate({
                inputRange: [ index - 1, index, index + 1 ],
                outputRange: [ layout.initWidth, 0, 0 ]
              });
              let opacity;
              if(Actions.lastActionType === 'Navigation/RESET'){
                opacity = position.interpolate({
                  inputRange: [ index - 1, index - 0.99, index, index + 0.99, index + 1 ],
                  outputRange: [ 0, 0, 0, 0, 0 ]
                });
              } else {
                opacity = position.interpolate({
                  inputRange: [ index - 1, index - 0.99, index, index + 0.99, index + 1 ],
                  outputRange: [ 0, 1, 1, 0, 0 ]
                });
              }

              return { opacity, transform: [{ translateX }] };
            }
          }
        }}
      >
```
For Router component from react-native-router-flux create simple reducer that will write action type to global "Actions" object.

```javascript
<Router
            createReducer={function(params){
              const newReducer = new Reducer(params);
              return (state, action) => {
                Actions.lastActionType = action.type;
                return newReducer(state, action);
              }
            }}
>
// ...childrens
</Router>
```

**Comment by rodrigooler** [comment]
+1

**Comment by omeraplak** [comment]
+1

**Comment by dale-french** [comment]
+1

**Comment by ztretterath** [comment]
this solution worked for my situation. Using navigate first followed by resetting.

`const navigateTo = (routeName) => {
	const actionToDispatch = NavigationActions.navigate({
                routeName,
		actions: [NavigationActions.reset({ index: 0 })],
	});
		return this.props.navigation.dispatch(actionToDispatch);
};

navigateTo('Main');`

**Comment by toandk** [comment]
This solution worked for me. Note that if you have 4 screen A, B, C, D and want to back from D to A, you have to call `NavigationActions.back` with **key of B**
`backToRoute = name => {
    const routes = screenNavigator.state.routes
    for (var i = 0; i < routes.length - 1; i++) {
      if (routes[i].routeName == name) {
        screenNavigator.dispatch(NavigationActions.back({ key: routes[i + 1].key }))
        break
      }
    }
  }`

**Comment by vonovak** [comment]
closing since this was fixed by https://github.com/react-community/react-navigation/pull/2520, but feel free to reopen in case the issue persists

**Comment by eballeste** [comment]
@vonovak #2520 does not work as intended.

After almost giving up on react-navigation I found your example for using the NavigatorService but it is incomplete, it's missing the return for when there are no nested navigators.

```javascript
function getRouteWithName(navigationState, name) {
  if (!navigationState) {
    return null;
  }
  const route = navigationState.routes[navigationState.index];

  // dive into nested navigators
  if (route.routes) {
    // NOTE +1 is because goBack accepts from, not to!
    const index = route.routes.findIndex(r => r.routeName === name);
    if (index > -1) {
      return route.routes[index + 1];
    }
    return getRouteWithName(route, name);
  } else {
    const index = navigationState.routes.findIndex(r => r.routeName === name);
    if (index > -1) return navigationState.routes[index + 1];
  }

  return null;
}
```

**Comment by joachimroeleveld** [comment]
@evollu that worked, thanks!!!

**Comment by dustturtle** [comment]
does this issues solved? In iOS we can simply push viewcontrollers by nav just disable the animation.

**Comment by pisangGoreng** [comment]
+ 1 ..

**Comment by dustturtle** [comment]
welcome to RNRF, easy case for that~

**Comment by luqmanrom** [comment]
How is it solved in RNRF @dustturtle

**Comment by andidev** [comment]
@luqmanrom it is not solved there as well. RNRF is based on React Navigation.
see https://github.com/aksonov/react-native-router-flux/issues/2713

**Comment by brentvatne** [comment]
can someone please create a new issue for this and include a link to an example reproducing it on https://snack.expo.io or github? please without any superfluous code. thanks!
