### ISSUE TITLE
PropTypes and React.createClass are deprecated

### ISSUE THREAD

**Issue by BerndWessels** [react-community/react-navigation#2019]
`react-navigation` seems to still be using `PropTypes` and `React.createClass` which is deprecated and throws annoying warnings now.

Is anybody already fixing this or do you want PRs to fix it?

**Comment by matthamil** [comment]
What version of react navigation are you using? Can you provide links to the source files that are causing these warnings? The `PropTypes` warnings should have been resolved with https://github.com/react-community/react-navigation/pull/1928 and https://github.com/react-community/react-navigation/pull/1968.

**Comment by szhigunov** [comment]
I have updated examples code, and haven't checked `react-navigation` sources yet. So PRs are welcome.

**Comment by jsteiner** [comment]
@matthamil it looks like the latest release (v1.0.0-beta.11) was released before some of those were merged. Maybe time for a new release?

**Comment by sanjayholla94** [comment]
@kelset I think this has been resolved with the latest release

**Comment by kelset** [comment]
it is :) Thanks for letting me know!

**Comment by ekimlinger** [comment]
Still seeing these issues on the latest version (^1.0.0-beta.19), am I missing something? 

I could not find any instances in this particular node_modules folder.

StackTrace:

```
2:58:47 PM
▼Warning: PropTypes has been moved to a separate package. Accessing React.PropTypes is no longer supported and will be removed completely in React 16. Use the prop-types package on npm instead. (https://fb.me/migrating-from-react-proptypes)
- node_modules\expo\src\Logs.js:187:24 in newConsoleFunc
- node_modules\fbjs\lib\warning.js:33:20 in printWarning
- node_modules\fbjs\lib\warning.js:57:25 in warning
- node_modules\react\cjs\react.development.js:2133:18 in get
- node_modules\react-native\Libraries\polyfills\babelHelpers.js:162:78 in interopRequireWildcard
- node_modules\metro-bundler\src\Resolver\polyfills\require.js:174:12 in loadModuleImplementation
- node_modules\react-navigation\src\navigators\StackNavigator.js:5:0 in <unknown>
- node_modules\metro-bundler\src\Resolver\polyfills\require.js:174:12 in loadModuleImplementation
- node_modules\react-navigation\src\react-navigation.js:27:19 in StackNavigator
* navigation\rootNavigator.js:8:15 in <unknown>
- node_modules\metro-bundler\src\Resolver\polyfills\require.js:174:12 in loadModuleImplementation
* App.js:15:0 in <unknown>
- node_modules\metro-bundler\src\Resolver\polyfills\require.js:174:12 in loadModuleImplementation
- node_modules\react-native-scripts\build\bin\crna-entry.js:27:19 in <unknown>
- node_modules\metro-bundler\src\Resolver\polyfills\require.js:174:12 in loadModuleImplementation
- node_modules\metro-bundler\src\Resolver\polyfills\require.js:119:45 in guardedLoadModule
2:58:48 PM
▼Warning: React.createClass is no longer supported. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement. (https://fb.me/migrating-from-react-create-class)
- node_modules\expo\src\Logs.js:187:24 in newConsoleFunc
- node_modules\fbjs\lib\warning.js:33:20 in printWarning
- node_modules\fbjs\lib\warning.js:57:25 in warning
- node_modules\react\cjs\react.development.js:2125:18 in get
- node_modules\react-native\Libraries\polyfills\babelHelpers.js:162:78 in interopRequireWildcard
- node_modules\metro-bundler\src\Resolver\polyfills\require.js:174:12 in loadModuleImplementation
- node_modules\react-navigation\src\navigators\StackNavigator.js:5:0 in <unknown>
- node_modules\metro-bundler\src\Resolver\polyfills\require.js:174:12 in loadModuleImplementation
- node_modules\react-navigation\src\react-navigation.js:27:19 in StackNavigator
* navigation\rootNavigator.js:8:15 in <unknown>
- node_modules\metro-bundler\src\Resolver\polyfills\require.js:174:12 in loadModuleImplementation
* App.js:15:0 in <unknown>
- node_modules\metro-bundler\src\Resolver\polyfills\require.js:174:12 in loadModuleImplementation
- node_modules\react-native-scripts\build\bin\crna-entry.js:27:19 in <unknown>
- node_modules\metro-bundler\src\Resolver\polyfills\require.js:174:12 in loadModuleImplementation
- node_modules\metro-bundler\src\Resolver\polyfills\require.js:119:45 in guardedLoadModule
2:58:49 PM
▼Warning: checkPropTypes has been moved to a separate package. Accessing React.checkPropTypes is no longer supported and will be removed completely in React 16. Use the prop-types package on npm instead. (https://fb.me/migrating-from-react-proptypes)
- node_modules\expo\src\Logs.js:187:24 in newConsoleFunc
- node_modules\fbjs\lib\warning.js:33:20 in printWarning
- node_modules\fbjs\lib\warning.js:57:25 in warning
- node_modules\react\cjs\react.development.js:2117:18 in get
- node_modules\react-native\Libraries\polyfills\babelHelpers.js:162:78 in interopRequireWildcard
- node_modules\metro-bundler\src\Resolver\polyfills\require.js:174:12 in loadModuleImplementation
- node_modules\react-navigation\src\navigators\StackNavigator.js:5:0 in <unknown>
- node_modules\metro-bundler\src\Resolver\polyfills\require.js:174:12 in loadModuleImplementation
- node_modules\react-navigation\src\react-navigation.js:27:19 in StackNavigator
* navigation\rootNavigator.js:8:15 in <unknown>
- node_modules\metro-bundler\src\Resolver\polyfills\require.js:174:12 in loadModuleImplementation
* App.js:15:0 in <unknown>
- node_modules\metro-bundler\src\Resolver\polyfills\require.js:174:12 in loadModuleImplementation
- node_modules\react-native-scripts\build\bin\crna-entry.js:27:19 in <unknown>
- node_modules\metro-bundler\src\Resolver\polyfills\require.js:174:12 in loadModuleImplementation
- node_modules\metro-bundler\src\Resolver\polyfills\require.js:119:45 in guardedLoadModule```

**Comment by jedrichards** [comment]
@ekimlinger I've found the same thing. Created a new issue:

https://github.com/react-community/react-navigation/issues/2979

**Comment by kelset** [comment]
@jedrichards @ekimlinger it's probably another library, as @matthamil stated above this library fixed the Prop dependencies a long time ago.

**Comment by kelset** [comment]
@hushicai @jedrichards @ekimlinger as you can see from [this search](https://github.com/react-community/react-navigation/search?p=2&q=propTypes&type=&utf8=%E2%9C%93) nowhere in the library we still use PropTypes from `React` aside from a single file in the example (`examples/NavigationPlayground/js/CustomTransitioner.js`).

So unless that error shows up when trying that example, it's not caused by this library.

**Comment by zygama** [comment]
Hello, i'm also seeing those warnings after an npm update from beta 13 to beta 21, i have warnings for: react.createClass, propTypes and checkPropTypes.

All of those warnings seems to be referred to react-navigation ...

**Comment by zygama** [comment]
I backed to beta 13 and not showing anymore

**Comment by gusgard** [comment]
The issue comes from this lines `import * as React from 'react';` that import PropTypes, checkPropTypes and createClass that are deprecated. To avoid this update to React 16.0.0 or fork the repo and replace  `import * as React from 'react';` with `import React from 'react';`. I already made a fork and update it, you can test it with https://github.com/gusgard/react-navigation#1b2c25336ff153f8f37f04cdd77bc3cab972736f

**Comment by kelset** [comment]
@gusgard you write "To avoid this update to React 16.0.0", meaning that this happens only when `react-native` < 0.49? 🤔

**Comment by gusgard** [comment]
@kelset  Yes the issue is only present when react-native < 0.50. Because with react <16.0.0 PropTypes is included and imported when this is executed `import * as React from 'react';`. With react 16 PropTypes, checkPropTypes and createClass are not included when you import all

**Comment by hushicai** [comment]
repost

**Comment by hushicai** [comment]
@gusgard repost.

**Comment by cccRaim** [comment]
so why use
```javascript
import * as React from 'react'
```
instead of
```javascript
import React from 'react'
```
