### ISSUE TITLE
DrawerNavigator buggy header

### ISSUE THREAD

**Issue by mkonicek** [react-community/react-navigation#216]
(Using react-navigation 1.0.0-beta.1)

In my ChatExample, tried using a `DrawerNavigator` (note that it's nested in a `StackNavigator`):

```
const HomeScreenNavigator = DrawerNavigator({
  Welcome: {
    screen: WelcomeScreen,
  },
  Chats: {
    screen: ChatListScreen,
  },
});
```

(Likely related to https://github.com/react-community/react-navigation/issues/165.)

![drawer_bug](https://cloud.githubusercontent.com/assets/346214/22697099/4ec94688-ed48-11e6-9fa8-dbebd8898218.gif)

**Comment by mkonicek** [comment]
cc @ericvicenti @grabbou @satya164

**Comment by mkonicek** [comment]
I'll try debugging what causes it.

**Comment by grabbou** [comment]
Any updates here @mkonicek? Need some help? :)

**Comment by mkonicek** [comment]
Hi @grabbou, I actually discovered a more important issue that I will be looking into first. Want to take this one? Thanks for offering help!

**Comment by satya164** [comment]
Beta 1 had a buggy version of drawer. This is probably not an issue anymore.

**Comment by dually8** [comment]
I'm curious how to fix an issue I'm having, if you don't mind me piggybacking off of this issue. I greatly appreciate any pointers.

![weirddrawer](https://cloud.githubusercontent.com/assets/6304040/22986168/af2746a2-f378-11e6-81f7-d5d0a4c44de3.png)

So, basically, I have a DrawerNav inside of a StackNav (list view, selecting a row goes to the shown view with the drawer on the right), and I'm wondering if there's some sort of config I'm missing somewhere that's affecting the header when the drawer is open vs when it's closed. I put a console.log inside of CardStack.js in the `_renderHeader` method to see what `headerConfig` returns. It returns the correct style on everything except for when it renders the header once the drawer is open. Not sure where to go from here. I appreciate any pointers. Thanks.

**Comment by mkonicek** [comment]
The issue described here is fixed in the latest version:
https://www.npmjs.com/package/react-navigation

But there is now a new one:
https://github.com/react-community/react-navigation/issues/374

**Comment by nico1510** [comment]
I removed the previous package in node_modules, installed the new version (beta-5), reset my packager cache and the bug is still there for me...
`
StackNavigator({
    root: {
        screen: DrawerNavigator({
            core: { screen: BasicScreen },
            folders: { screen: FoldersScreen },
        })
    }
})
`
On the core screen I have a `header: {
            visible: false,
        },` in my `navigationOptions` because I don't want any header on this screen. When opening the Drawer however, the header shows up just like in the gif you uploaded here. So for me this issue still exists...

**Comment by ferprez** [comment]
Any updates ?
