### ISSUE TITLE
Header of first screen rendered behind second screen header

### ISSUE THREAD

**Issue by cychiuae** [react-community/react-navigation#229]
I made my router and screen as following

```js
import React from 'react';
import {
  Button,
  ScrollView,
} from 'react-native';
import {
  StackNavigator,
} from 'react-navigation';
import SampleText from './SampleText';

const MyNavScreen = ({ navigation, banner }) => (
  <ScrollView>
    <SampleText>{banner}</SampleText>
    <Button
      onPress={() => navigation.navigate('Profile', { name: 'Jane' })}
      title="Go to a profile screen"
    />
    <Button
      onPress={() => navigation.goBack(null)}
      title="Go back"
    />
  </ScrollView>
);

const MyHomeScreen = ({ navigation }) => (
  <MyNavScreen
    banner="Home Screen"
    navigation={navigation}
  />
);
MyHomeScreen.navigationOptions = {
  title: 'Welcome',
};

const MyPhotosScreen = ({ navigation }) => (
  <MyNavScreen
    banner={`${navigation.state.params.name}'s Photos`}
    navigation={navigation}
  />
);
MyPhotosScreen.navigationOptions = {
  title: 'Photos',
};

const MyProfileScreen = ({ navigation }) => (
  <MyNavScreen
    banner={
      `${navigation.state.params.mode === 'edit' ? 'Now Editing ' : ''
      }${navigation.state.params.name}'s Profile`
    }
    navigation={navigation}
  />
);
MyProfileScreen.navigationOptions = {
  header: ({ state, setParams }) => ({
    title: `${state.params.name}'s Profile!`,
    tintColor: '#007AFF',
    // Render a button on the right side of the header.
    // When pressed switches the screen to edit mode.
    right: (
      <Button
        title={state.params.mode === 'edit' ? 'Done' : 'Edit'}
        onPress={() => setParams({ mode: state.params.mode === 'edit' ? '' : 'edit' })}
      />
    ),
  }),
};

const SimpleStack = StackNavigator({
  Home: {
    screen: MyHomeScreen,
  },
  Profile: {
    path: 'people/:name',
    screen: MyProfileScreen,
  },
  Photos: {
    path: 'photos/:name',
    screen: MyPhotosScreen,
  },
});

export default SimpleStack;
```

![screen shot 2017-02-08 at 3 53 22 pm](https://cloud.githubusercontent.com/assets/10144357/22728101/1bc3513c-ee17-11e6-8c01-b6b25179d381.png)

When I navigated to the `MyProfileScreen`, the header of `MyHomeScreen` appeared behind the header of `MyProfileScreen`

![screen shot 2017-02-08 at 3 53 32 pm](https://cloud.githubusercontent.com/assets/10144357/22728105/1e6a6510-ee17-11e6-834a-238edbfea90b.png)

When I went back to `MyHomeScreen` and then navigate to `MyProfileScreen` again, it won't happen again.

![screen shot 2017-02-08 at 3 53 44 pm](https://cloud.githubusercontent.com/assets/10144357/22728243/e0888f5a-ee17-11e6-8f9f-d7503f0c07d3.png)

https://github.com/cychiuae/react-navigation/compare/master...cychiuae:header-bug-example

By the way, great job guys for building this library :)

**Comment by satya164** [comment]
What's your React Native version? Can you update to the latest version and see if it still happens?

**Comment by cychiuae** [comment]
@satya164 I am using RN 0.41.0 and I am working on master of `react-navigation`

**Comment by cychiuae** [comment]
I just found out if I set `useNativeDriver` to `false`, the bug won't occur. Any ideas for that?

**Comment by satya164** [comment]
Hmm. There was a similar bug, but I thought it was fixed.

cc @janicduplesis any idea why this might happen? ideally title should go to 0 opacity

**Comment by grabbou** [comment]
@satya164 just a reminder that mention didn't work, probably try on Slack.

**Comment by janicduplessis** [comment]
Theres a pr for native animations that fixes some edge cases with restoring default values that still isnt merged, might be related to that. If you can try https://github.com/facebook/react-native/pull/11819 and confirm if it fixes the issue it would be great, I'll try to get it merged asap.

**Comment by grabbou** [comment]
I can also confirm that for some reason when I was playing around with back button label, I've noticed the first time I push / back, there are small glitches, 2nd time it runs perfectly fine.

**Comment by cychiuae** [comment]
@janicduplessis 
Your PR(facebook/react-native#11819) fixes the problem. Do you think RN 0.42 will include your fixes?

**Comment by grabbou** [comment]
I'll cherry-pick it as soon as it lands.

**Comment by cychiuae** [comment]
Thanks a lot :)

**Comment by janicduplessis** [comment]
Yea I bugged people to get it reviewed yesterday, we'll get it in 0.42

**Comment by zeroryu** [comment]
can we reopen this since the PR hasnt been merged with 0.42. it's misleading to say that this bug has been fixed

**Comment by satya164** [comment]
Re-opening this issue doesn't achieve anything. It's a bug in native animations in React Native which has an open PR and not a bug in React Navigation.

**Comment by EmielM** [comment]
Still an issue with 0.43. What's the status upstream, @janicduplessis ?

**Comment by EmielM** [comment]
Right, this finally seems to be fixed in react-native 0.44-rc0 (current master branch)!

**Comment by janicduplessis** [comment]
Yes, sorry this took so long to land, lot of back and forth on that PR. The same bug also exists on Android and the PR to fix it is still waiting for review.

**Comment by ptc-jhughes** [comment]
Had a hard time following this but to summarize, it seems like this is fixed and will ship with 0.44-rc0 for iOS (facebook/react-native#11819). And the Android version is yet to be merged and is facebook/react-native/pull/12842

**Comment by janicduplessis** [comment]
Exactly, thanks for the summary :)

**Comment by gregblass** [comment]
I'm using 0.44 and while it does seem to be better, I just saw it happen again on iOS.

**Comment by huhuanming** [comment]
not happen again in 0.44

**Comment by gregblass** [comment]
Just saw it again, so 2 times in the course of about 8 hours. So I'd estimate that its happening to me about 1 out of every 100-300 navigations if I had to give a rough ballpark.

**Comment by JAStanton** [comment]
I can reproduce it very easily, but it seems to eventually clean itself up:
![bug](https://cloud.githubusercontent.com/assets/645300/26267787/c79eadb2-3ca0-11e7-9d91-c3d3e184eb0a.gif)


```json
"react": "16.0.0-alpha.6",
"react-native": "0.44.0",
"react-navigation": "^1.0.0-beta.9"
```
copy and pasted example code from example stack router:

<details>
  <summary>Code example</summary>

```jsx
/**
 * @flow
 */

import React from 'react';
import { Text, AppRegistry, Button, ScrollView } from 'react-native';
import { StackNavigator } from 'react-navigation';

const MyNavScreen = ({ navigation, banner }) => (
  <ScrollView>
    <Text>{banner}</Text>
    <Button
      onPress={() => navigation.navigate('Profile', { name: 'Jane' })}
      title="Go to a profile screen"
    />
    <Button
      onPress={() => navigation.navigate('Photos', { name: 'Jane' })}
      title="Go to a photos screen"
    />
    <Button onPress={() => navigation.goBack(null)} title="Go back" />
  </ScrollView>
);

const MyHomeScreen = ({ navigation }) => (
  <MyNavScreen banner="Home Screen" navigation={navigation} />
);

MyHomeScreen.navigationOptions = {
  title: 'Welcome',
};

const MyPhotosScreen = ({ navigation }) => (
  <MyNavScreen
    banner={`${navigation.state.params.name}'s Photos`}
    navigation={navigation}
  />
);

MyPhotosScreen.navigationOptions = {
  title: 'Photos',
};

const MyProfileScreen = ({ navigation }) => (
  <MyNavScreen
    banner={`${navigation.state.params.mode === 'edit' ? 'Now Editing ' : ''}${navigation.state.params.name}'s Profile`}
    navigation={navigation}
  />
);

MyProfileScreen.navigationOptions = props => {
  const { navigation } = props;
  const { state, setParams } = navigation;
  const { params } = state;
  return {
    headerTitle: `${params.name}'s Profile!`,
    // Render a button on the right side of the header.
    // When pressed switches the screen to edit mode.
    headerRight: (
      <Button
        title={params.mode === 'edit' ? 'Done' : 'Edit'}
        onPress={() =>
          setParams({ mode: params.mode === 'edit' ? '' : 'edit' })}
      />
    ),
  };
};

const SimpleStack = StackNavigator({
  Home: {
    screen: MyHomeScreen,
  },
  Profile: {
    path: 'people/:name',
    screen: MyProfileScreen,
  },
  Photos: {
    path: 'photos/:name',
    screen: MyPhotosScreen,
  },
});

AppRegistry.registerComponent('HeaderTest', () => SimpleStack);
```

</details>

**Comment by satya164** [comment]
Could there be a possible regression? cc @janicduplessis

**Comment by janicduplessis** [comment]
Might be another edge case, I'll investigate

**Comment by janicduplessis** [comment]
@satya164 @JAStanton I did some testing and this bug is not related to native animations, I tested with it disabled and still reproduced the issue. Using @JAStanton's code it is very easy, just navigate to profile screen, use back gesture, navigate to photos, use back gesture. (only happens when using back gesture, it never happened when using the back button).

**Comment by janicduplessis** [comment]
We might want to open a new issue for this since it's not related to this one.

**Comment by satya164** [comment]
Hmm.. That's pretty weird. @JAStanton can you open a new issue?

**Comment by JAStanton** [comment]
@satya164 @janicduplessis separate issue has been filed
