### ISSUE TITLE
Undefined is not an object(evaluating '_ref4.route') with Android

### ISSUE THREAD

**Issue by minhlv3107** [react-community/react-navigation#3020]
After I upgrade to version "react-navigation": "^-beta 1.0.0.20" 
On ios runs good but on android and fails as follows: Undefined is not an object(evaluating '_ref4.route')

| software         | version
| ---------------- | -------
| react-navigation | beta 1.0.0.20
| react-native     | 0.48.4
| node             | 8.9.1
| npm or yarn      | npm 5.5.1
![screenshot_1511237612](https://user-images.githubusercontent.com/30583152/33054641-0dfeb088-cead-11e7-8d30-78679df6c500.png)

**Comment by giogodo** [comment]
**I'm got the same problem...**

Here my package.json

```
{
	"name": "testApp",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"start": "node node_modules/react-native/local-cli/cli.js start",
		"test": "jest"
	},
	"dependencies": {
		"react": "16.0.0",
		"react-native": "0.50.3",
		"react-native-maps": "^0.17.1",
		"react-navigation": "^1.0.0-beta.20"
	},
	"devDependencies": {
		"babel-jest": "21.2.0",
		"babel-preset-react-native": "4.0.0",
		"jest": "21.2.1",
		"react-test-renderer": "16.0.0"
	},
	"jest": {
		"preset": "react-native"
	}
}

**Comment by valinaga** [comment]
Hi,

Same issue on android for 1.0.0-beta.20. On 1.0.0-beta.19 it was fine.
``
  "message": "undefined is not an object (evaluating '_ref4.route')",
  "stack": [
    {
      "functionName": "_getOnPress",
      "lineNumber": 110,
      "columnNumber": 44,
      "fileName": "/Users/vali/MyWorks/react/wishbox/node_modules/react-navigation/src/views/TabView/TabView.js"
    },
    {
      "functionName": "_handleOnPress",
      "lineNumber": 127,
      "columnNumber": 31,
      "fileName": "/Users/vali/MyWorks/react/wishbox/node_modules/react-navigation/src/views/TabView/TabBarTop.js"
    },
    {
      "functionName": "onPress",
      "lineNumber": 466,
      "columnNumber": 33,
      "fileName": "/Users/vali/MyWorks/react/wishbox/node_modules/react-native-tab-view/src/TabBar.js"
    }
  ]
}
``
The issue is here:
``
-getOnPress = (previousScene: TabScene, {route}: TabScene ) => {
``
Looks like route is not part of the scene.
Any fix?
Thanks

**Comment by wangbingqiong** [comment]
I'm got the same problem...

**Comment by vonovak** [comment]
pease read the release notes: https://github.com/react-community/react-navigation/releases

**Comment by valinaga** [comment]
@vonovak the breaking changes break the normal behaviour in android. It does not matter if you try or not to overwrite the navigationOptions with tabBarOnPress.

**Comment by valinaga** [comment]
for now downgrading to 1.0.0-beta.19 fix the problem.

**Comment by kelset** [comment]
@valinaga @minhlv3107 @giogodo can any of you provide a repo that reproduces the issue? Because as @vonovak said we introduced this Breaking Change with `beta.20` but I can't understand why it happens to you (if you have not used tabBarOnPress).

(ping @pietro909)

**Comment by vonovak** [comment]
@valinaga @giogodo @minhlv3107 would you be willing to ship a PR to fix this?

**Comment by shlomokraus** [comment]
I've setup a fresh react native project with only a simple TabNavigator and I also encountered this behavior on beta.20 under Android. It is simple to reproduce. on ios it works fine.

**Comment by valinaga** [comment]
@kelset It's strange because I only have:
```
...
    tabBarComponent: TabBar,
    tabBarPosition: 'bottom',
    lazy: true,
    backBehavior: 'none',
    headerMode: 'none',
    scrollEnabled: false,
    swipeEnabled: false,
    navigationOptions: {},
}
```
in my TabNavigator. Maybe because the `tabBarComponent` ?

**Comment by spencercarli** [comment]
I've reproduced and am working on a fix. We should ship beta.21 with this and another bug fix today.

**Comment by spencercarli** [comment]
Fixed and released in beta.21! Thanks for reporting.

**Comment by pietro909** [comment]
Sorry, I saw it now. We never ran into this one, because we don't use `TabBarTop` (both IOS and Android).

I think we could add some tests to cover these cases.

**Comment by wildseansy** [comment]
This is still broken for my team, using version beta.21.  Anyone else seeing this still?

**Comment by kelset** [comment]
@wildseansy have you tried do a clean install of the modules? It's fixed for me with beta21

**Comment by ahmetilhann** [comment]
@wildseansy No. It works after you update

**Comment by Jaewoook** [comment]
I have the same error with `react-native-material-bottom-navigation` and `react-navigation@1.0.0-beta.21`. I want to know why the third party navigation working incorrectly and the solution.

**Comment by wildseansy** [comment]
@Jaewoook - yeah I use `react-native-material-bottom-navigation` too, and it crashes with this stacktrace on android.  I reverted to beta.19 too.

**Comment by kelset** [comment]
@Jaewoook @wildseansy then I guess you should open an issue on that library 😕

**Comment by riki9925** [comment]
yeaahh thank you for everyone i try beta.21 work fine
