### ISSUE TITLE
Back button in header not doing anything

### ISSUE THREAD

**Issue by mikeaxle** [react-community/react-navigation#318]
With redux connected to react-navigation, the default back button in the header does not do anything. When i check the debugger info, tapping the back button in the header just adds the current screen to the navigation state. How do i make it go to the previous screen (Redux is connected to react-navigation).

**Comment by ericvicenti** [comment]
How have you connected redux to the navigator? This issue is not very specific, so I'm closing until you provide more details and rename the issue to be more clear.

In general, if you want to see how a navigator would go back, you can call `MyNavigator.router.getStateForAction(NavigationActions.back(), lastState)`. If you're using redux in your app, you are expected to manually call this on the router from your app's reducer, in order to get the new navigation state after going back.

**Comment by mikeaxle** [comment]
@ericvicenti 
yes, i have connected redux to the navigator. What I mean is that the default back button that appears in the header after moving from one screen to another does not actually navigate back to the previous screen when tapped. 

![screen shot 2017-02-13 at 7 22 54 pm](https://cloud.githubusercontent.com/assets/15367382/22894558/1477ae46-f222-11e6-829f-42b69df85c18.png)

How do get that back button to navigate to the previous screen? I managed to set up the android hardware button to do that by making it dispatch an action. For the back button that appears in the header, I do not know how to do it. Please help

**Comment by chrissm79** [comment]
Just experienced this myself (with nested navigation) and I fixed it by calling `goBack(null)` which is passed in through `header` in `navigationOptions`:

*If I just called `goBack()` (without the null) it didn't do anything)*

```js
const App = StackNavigator({
  Login: { screen: Login },
  // ...
}, {
  navigationOptions: {
    header({ goBack }) => ({
      left: (<BackButton onPress={() => goBack(null)} />)
      // ...
    })
  }
})
```

**Comment by ericvicenti** [comment]
Oops! @chrissm79 is right, you need to pass null. Very sorry about that confusion, I had been familiar with a previous API where the back action did not specify the key.

**Comment by mikeaxle** [comment]
chrissm79 its still not working, i have resorted to making an action that takes a user to the previous page and attaching it to the header button, does going back in this way mess with the navigation stack in any way?

**Comment by ericvicenti** [comment]
If you can describe your bug in terms of a failing test case, then it will be super clear what behavior difference you expect from the router, and it will be much easier for the project maintainers to fix the problem.

**Comment by mikeaxle** [comment]
@ericvicenti  thanks, eric. I will remember that next time. I used navigation.dispatch in the header. like this: ```javascript  onPress={() => navigation.dispatch({type: 'back_screen'})}> ``` and NavigationActions.back() in the reducer: ```javascript case 'back_screen': return AppNavigator.router.getStateForAction(NavigationActions.back(), state); ``` that worked finally.
