### ISSUE TITLE
RN 42 - Expected array with count 16, but count is 2

### ISSUE THREAD

**Issue by fabriciovergal** [react-community/react-navigation#550]
Trying to integrate React-Navigation with RN42 project.
When I add any navigator the apps stop due to this error:

![simulator screen shot 2 mar 2017 18 24 44](https://cloud.githubusercontent.com/assets/5910915/23518966/84d007fa-ff75-11e6-9a26-f65cd19cf226.png)

**Comment by MovingGifts** [comment]
@fabriciovergal I also have the same issue after upgrading RN to 0.42, but I that is even before integrating `react-navigation`. Just curious, are you using `react-native-router-flux` at all?
I ask because I am using it, and it might be from it but I am not 100% sure.

Also, please let us know if you figure out what it is.

**Comment by fabriciovergal** [comment]
No, react-navigation is the only navigation lib in my boilerplate project.

**Comment by abeauvois** [comment]
@MovingGifts Same issue, I'm using react-native-router-flux and when not using it the error disappears.

**Comment by grabbou** [comment]
Confirmed

**Comment by grabbou** [comment]
I can confirm that it happens on 0.42.0 and above.

**Comment by MovingGifts** [comment]
@abeauvois We'll just have to wait until grabbou gets it to work with his team.
@grabbou did you mean next release of RN as in 0.43, so in about a month?

**Comment by drblmb** [comment]
I had this same error, but after stopping the packager, and rebuilding, the error went away.

**Comment by stverhae** [comment]
same issue here, restarting packager doesnt help though ..

**Comment by matthamil** [comment]
@MovingGifts I think @grabbou is referring to the next release of `react-navigation`.

**Comment by MovingGifts** [comment]
@matthamil Yeah, I wasn't sure 100% since they both get new releases.
@grabbou Can you please update this thread to let us know when it's resolved?

**Comment by grabbou** [comment]
There is work in progress on next release, no dates yet. I have my list to do as well as others, I guess this week we will ship a new updated version.

**Comment by raphaelameaume** [comment]
Was running through the same issue after trying to update react-native with a simple `npm install`. Following the upgrading guide from [react-native documentation](https://facebook.github.io/react-native/docs/upgrading.html) and the `react-native-git-upgrade` module solved the problem.

**Comment by cgarg** [comment]
I was also facing the same issue. 
`npm install -g react-native-git-upgrade`
` react-native-git-upgrade`
`rm -rf node_modules/`
`npm install`
All this solved the issue.
Thanks! @raphaelameaume

**Comment by grabbou** [comment]
So I am having a workshop tomorrow in SF and so, I am quite busy over here.
But I'll have more time during the weekend and will try to get back to you
and resolve that issue.

**Comment by felangga** [comment]
Having the same problem. 
@cgarg solution not working for me :(

**Comment by yccphp** [comment]
I also encountered this question, who knows why ?

**Comment by zawarudo** [comment]
@cgarg Solution also did not work for me.

I had to give up and just do `react-native upgrade` to fix it for me.

**Comment by felangga** [comment]
I had to downgrade to 0.41.0

**Comment by Jakevin** [comment]
0.41.2 OK
0.42 will red screen ....

**Comment by Jakevin** [comment]
[stackoverflow](http://stackoverflow.com/questions/42765165/react-native-0-42-expected-array-with-count-16)
I try to del ios/build and rerun " react-native run-ios".

It work for me

**Comment by ericvicenti** [comment]
If you clear out your native build and go again, it should work: http://stackoverflow.com/questions/42765165/react-native-0-42-expected-array-with-count-16

**Comment by MovingGifts** [comment]
@ericvicenti how do you clear the native build?

**Comment by GuillaumeMunsch** [comment]
You remove the `build/` directory in either the `ios/` or the `android` folder.

Worked for me

**Comment by momotofu** [comment]
Removing the build directory and then running `react-native run-ios` doesn't fix it on my end. Any ideas?

**Comment by cooperka** [comment]
For me the issue was out-of-sync react-native versions across the main package and the example app. Fixed in https://github.com/react-community/react-navigation/pull/1144.

**Comment by jsanchezs** [comment]
I tried everything wrote in this issue and I still having the same problem. Any news?
