### ISSUE TITLE
Hundreds of flowtype errors

### ISSUE THREAD

**Issue by kylpo** [react-community/react-navigation#81]
Using version `0.36.0` of `flow-bin`, adding `react-navigation` to the project results in ~350 flow errors. Also seeing this in `react-navigation`'s example repos on a fresh clone.

I was hoping I could get around this with a flowconfig like:

```
[ignore]
.*/node_modules/react-navigation/.*
...

[libs]
node_modules/react-navigation/lib-rn
...

```

But still has 150+ errors.

If I am not the only one seeing this, please consider removing the Flow declaration files until they are working with the current React Native Flowtype version. I don't want to ignore the whole module and suppress each `import ... from 'react-navigation'`.

Thanks for your work on this! So excited to use `react-navigation`!

**Comment by ericls** [comment]
I'm also seeing this issue.

**Comment by satya164** [comment]
Removing flow declaration files won't fix the issue as long as we have annotations in the source code. You can ignore the errors in your flow config for now.

Under `[ignore]`, add `.*/node_modules/react-navigation/.*`
Under `[options]`, add `module.name_mapper='^react-navigation$' -> 'emptyObject'`

example config - https://github.com/satya164/PocketGear/blob/ea0cf98dae1b86f19aab874037a0aaeb25bfa464/.flowconfig

**Comment by kylpo** [comment]
Thanks @satya164! Nice trick with `module.name_mapper`.

**Comment by ericvicenti** [comment]
@satya164 recently cleaned up or suppressed all the remaining flow errors, so this should be resolved!

**Comment by kylpo** [comment]
Thanks for your work on this, @satya164! I still see errors in the test files, but ignoring them with `.*/node_modules/react-navigation/.*-test.js` does the trick.
