### ISSUE TITLE
Error on RN 0.43.0

### ISSUE THREAD

**Issue by TaiPA** [react-community/react-navigation#901]
```
Loading dependency graph, done.
error: bundling: Error
    at DependencyGraph._getAbsolutePath (/Users/taipa/develop/react-native/RNApp04/node_modules/react-native/packager/src/node-haste/index.js:285:11)
    at load.then (/Users/taipa/develop/react-native/RNApp04/node_modules/react-native/packager/src/node-haste/index.js:228:28)
    at process._tickCallback (internal/process/next_tick.js:109:7)
Bundling `index.ios.js`  0.0% (0/1), failed.
error: bundling: UnableToResolveError: Unable to resolve module `react/lib/ReactComponentWithPureRenderMixin` from `/Users/taipa/develop/react-native/RNApp04/node_modules/react-navigation/src/views/Header.js`: Module does not exist in the module map or in these directories:
  /Users/taipa/develop/react-native/RNApp04/node_modules/react-navigation/node_modules/react/lib
,   /Users/taipa/develop/react-native/RNApp04/node_modules/react/lib
```

**Comment by chandu0101** [comment]
Fix is in master, point to github repo in package.json

**Comment by TaiPA** [comment]
Thank you !!!
It is fixed for me.

**Comment by bionicbrad** [comment]
Just wondering - since I just upgraded to RN 0.43.0, I find that if I use the StackNavigator to display views with the mode set to 'modal', the modal screen on iOS can no longer be dismissed with a downward swipe.  Is this a known issue, or something else that has changed recently?

**Comment by JoeLanglois** [comment]
Still have a related error this morning using the github master repo in my package.json...
`Unable to resolve module 'react/lib/ReactDebugCurrentFrame from [...]`

**Comment by ericvillemure** [comment]
The following fixed it for me:

npm install react-navigation@https://github.com/react-community/react-navigation.git --save

**Comment by xeonproc** [comment]
@ericvillemure - Your fix worked for me as well.

**Comment by jonatassaraiva** [comment]
fixed 

`npm install react-navigation@https://github.com/react-community/react-navigation.git --save`

**Comment by ericvicenti** [comment]
Sounds like this is resolved by using master, and should be fixed in the next release

**Comment by aarboleda1** [comment]
still not working for me
@ericvillemure, what version of react/react-native are you on?
    "react": "16.0.0-alpha.6",
    "react-native": "0.43.2",

**Comment by ariona** [comment]
@aarboleda1 I am stuck with this a hour, but this fix work for me: installing from github repo.
`npm install react-navigation@https://github.com/react-community/react-navigation.git --save`

"react": "16.0.0-alpha.6",
"react-native": "0.43.2",

**Comment by RuiDamiao** [comment]
@ericvillemure  Your fix worked for me. Thanks

**Comment by jryanhaber** [comment]
I tried this:
npm install react-navigation@https://github.com/react-community/react-navigation.git --save

But got this error:
npm WARN react-navigation@1.0.0-beta.9 requires a peer of react@* but none was installed.

After already installing react-native-cli... 

Jonathans-MBP-2:newProjects neo$ npm install -g react-native-cli
/usr/local/bin/react-native -> /usr/local/lib/node_modules/react-native-cli/index.js
/usr/local/lib
└── react-native-cli@2.0.1 

Am I missing something?

**Comment by bencodezen** [comment]
@jryanhaber I found that if you manually install the missing peer dependency it works. 

`npm install --save react@*`

Hope this works for you!

**Comment by zilahir** [comment]
i am still having this issue with the following setup: 

`{
  "name": "SplashWalls",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "": "",
    "mongodb": "^2.2.31",
    "react": "^15.6.1",
    "react-native": "0.47.1",
    "react-navigation": "git+https://github.com/react-community/react-navigation.git"
  },
  "devDependencies": {
    "babel-jest": "20.0.3",
    "babel-preset-react-native": "2.1.0",
    "jest": "20.0.4",
    "react-test-renderer": "16.0.0-alpha.12"
  },
  "jest": {
    "preset": "react-native"
  }
}
`

any idea how to solve this issue?:

**Comment by Miladvp** [comment]
> The following fixed it for me:
> 
> npm install react-navigation@https://github.com/react-community/react-navigation.git --save



wowwwwww thank you bro - you save me since last night
