### ISSUE TITLE
gesturesEnabled not working in `modal` mode

### ISSUE THREAD

**Issue by bionicbrad** [react-community/react-navigation#902]
Since upgrading to RN 0.43.0, using gestures for dismissing a screen presented using the StackNavigator is no longer working.  I was leaving this default before (i.e., true on iOS, false on Android), but it stopped working on iOS after the RN upgrade.  Now, the default iOS setting and/or specifying it deliberately in the navigator options (by specifying cardStack: { gesturesEnabled: true }) has no effect.

Any suggestions?

**Comment by VictorVolovik** [comment]
same issue after migrating to RN 0.43.1 from 0.42

**Comment by smkhalsa** [comment]
+1

**Comment by mesbahsabur** [comment]
+1 

`screen: ExampleStack,
      navigationOptions: {
        header: {
          gesturesEnabled: false,
        },
      },`

Has no effect in iOS

**Comment by bionicbrad** [comment]
@mesbahsabur - that doesn't look like it applies.  Does it work for you with gesturesEnabled: true (i.e., can you swipe down to dismiss a modal screen?)

**Comment by bionicbrad** [comment]
P.S., this is still present with RN 0.43.3

**Comment by mesbahsabur** [comment]
Yes it works! @bionicbrad 

Here is a bit more of the code, I can toggle gesture modes this way...

```
export const TextonlyStack = StackNavigator(
  {
    Textonly: {
      screen: Textonly,
      navigationOptions: {
        title: 'Textonly',
      },
    },
  },
  {
    navigationOptions: {
      cardStack: {
        gesturesEnabled: false,
      }
    },
  },
);

export const Root = StackNavigator(
  {
    Tabs: {
      screen: Tabs,
    },
    Settings: {
      screen: SettingsStack,
    },
    Slideshow: {
      screen: SlideshowStack,
    },
    Movie: {
      screen: MovieStack,
    },
    Textonly: {
      screen: TextonlyStack,
    },
  },
  {
    mode: 'modal',
    headerMode: 'none',
  }
);
```

**Comment by blaues0cke** [comment]
Can also confirm that the code from @mesbahsabur is working on RN 0.42

```
const ModalStackNavigator = StackNavigator({
    ...
}, {
    mode:       'modal',
    navigationOptions: {
        cardStack: {
            gesturesEnabled: false,
        }
    }
});
```

completely disables the "drag down" gesture to close a modal view.

**Comment by pxue** [comment]
@mesbahsabur are you saying by specifying `gesturesEnabled: false` on `TextonlyStack` will fix the modal gestures? Currently I'm unable to get modal swipe down gesture to work.

**Comment by mesbahsabur** [comment]
@pxue No exactly, setting gesturesEnabled to false completely disables the swipe down gesture in iOS. This also fixed issues with ScrollView.

I haven't found a way to enable gestures as well as use a ScrollView without facing scrolling issues. But then again, usually this would lead to bad UX anyway.

**Comment by bionicbrad** [comment]
Ok...I don't get it.  I want gesturesEnabled: true - this is what not working for me.  @mesbahsabur , you seem to be talking about getting gesturesEnabled: false to work...since the 'true' state is already not working, I don't see how this helps.

**Comment by mesbahsabur** [comment]
I see, my mistake, I misunderstood your issue. I had the exact opposite issue where I could not disable the gestures. I am on RN 0.43 and gestures are enabled automatically in modal view in iOS and they work just fine. If you haven't already, perhaps you can experiment with my way of nesting?

**Comment by wilomgfx** [comment]
Indeed disabling it doesnt work on 0.43.3 either

**Comment by bionicbrad** [comment]
Ok, here's my simple stacknavigator - from what I understand from the current documentation, the gesturesEnabled config goes at the root of the config object (second parameter, a.k.a., StackNavigatorConfig):

```javascript
const SimpleNav = StackNavigator({
  Home: { screen: Home },
  Login: { screen: Login },
  Settings: {screen: Settings }
},{
  mode: 'modal',
  gesturesEnabled: false
});
```

With the latest react-navigation from the master branch (as-of a few hours ago), and React-Native 0.43.3, I get the following behaviours:

- If mode=='modal' any screen displayed on top of the 'Home' screen cannot be dismissed by gesture
- If mode == 'card', any screen displayed on top of the 'Home' screen **can** be dismissed by gesture

In no situation, have I been able to get the gesturesEnabled option to have any influence...but apart from that, the default in iOS for gesturesEnabled is supposed to be true.  This is the case for 'card' mode, but does not work for me in 'modal' mode...

Is it just me?  Am I doing something wrong, or missing something somewhere?

**Comment by kslat3r** [comment]
The following worked for me with latest beta7:

`
Auth.navigationOptions = {
  title: 'Peg',
  header: {
    left: null,
  },
  cardStack: {
    gesturesEnabled: false,
  },
};
`

**Comment by smkhalsa** [comment]
I'm also having issues with enabling gestures (i.e. swipe down to close) on a modal CardStack

**Comment by smkhalsa** [comment]
@satya164 @grabbou were there any breaking changes that would affect gestures on a modal CardStack that weren't documented? I just went back through and double checked my code against the docs, but I still can't get my modal CardStack to respond to a swipe down gesture.

**Comment by RUIFERNANDE5** [comment]
How can I disable the gestures on iOS?

`export const Router = StackNavigator({
    Auth: {
        screen: Auth,
    },
    Dashboard : {
        screen: Drawer,
    },
}, {
    headerMode: 'none',
    cardStack: {
        gesturesEnabled: false,
    },
});`

Doesn't seem to work..

**Comment by grabbou** [comment]
`gesturesEnabled` is now part of `navigationOptions`, see docs: https://reactnavigation.org/docs/navigators/stack#gesturesEnabled

That should be either set on a screen or inside `navigationOptions` for a given stack.

There's a chance it's been broken (CC: @ericvicenti), might be worth to pay attention to it.

**Comment by smkhalsa** [comment]
I believe it is broken.

Here's my StackNavigatorConfig:

```
{
  mode: 'modal',
  headerMode: 'none',
  navigationOptions: {
    gesturesEnabled: true,
  },
}
```

The modal view is not responding to gestures.

**Comment by stevenconner** [comment]
I am also having this problem, have tried settings gesturesEnabled: false in several different ways and can't get it to prevent ios from swiping screens away

**Comment by maxkomarychev** [comment]
@stevenconner your issue might be fixed by this PR https://github.com/react-community/react-navigation/pull/1147 approved yesterday.

**Comment by onlydave** [comment]
Fixed for `mode: 'card'` but not for modal. If you switch to using master instead of beta7 you need to change to this format
```
{
  mode: 'card',
  navigationOptions: {
    gesturesEnabled: true,
  },
}
```

Hopefully a fix for mode: modal will come soon

**Comment by aqnaruto** [comment]
ok,  does anybody know how to make same goback-gesture on android just like ios ??
i need gobak-gesture and i am strugled with this #1400

**Comment by manuTro** [comment]
Has been `gestureEnabled` fixed ? To me it's still not working

**Comment by hegelstad** [comment]
For me (1.5.0) it works if i put `gesturesEnabled: false` as `static navigationOptions = () => ` in each screen that is a part of the stack that has mode == modal.

**Comment by dwilt** [comment]
I'm using `2.17.0` and what @olegwn suggested didn't work for me. For some reason, having the a navigator wrap the screen I wanted to disable/enable the gestures programmatically (via `setParams`) didn't work. I even tried adding `gesturesEnabled: false` (or `true`) on the "RootStack" navigator to no avail. What did work though, and was quite simpler was removing the wrapped navigator from the screen I wanted to toggle the gestures on:

*Routes* - notice there is nothing about `gesturesEnabled` anywhere.
```js
const RootStack = createStackNavigator(
  {
    MainTabsStack,   
    Recorder, // <---- This is my modal
  },
  {
    mode: 'modal', // <--- Using `modal`, not `card`
    initialRouteName: 'MainTabsStack',
    headerMode: 'none',
    transitionConfig,
  },
);
```
And then inside of `Recorder`...
```jsx
static navigationOptions = ({
  navigation: {
    state: { params = { gesturesEnabled: true } },
  },
}) => ({
  header: null,
  gesturesEnabled: params.gesturesEnabled, // <--- THIS IS ALL THAT IS NEEDED 
});
```

And as I said, I would toggle the value of `gesturesEnabled` via [setParams](https://reactnavigation.org/docs/en/headers.html#updating-navigationoptions-with-setparams)

**Comment by david-arteaga** [comment]
I got it working in RN 0.58.1 with react-navigation 3.0.9 on iOS  with the following
```js
const ModalNavigator = createStackNavigator(
  {
    Main: {
      screen: ToursNavigator,
      navigationOptions: {
        header: null,
      },
    },
    SomeModalScreen: {
      screen: MyModalScreen,
      navigationOptions: { gesturesEnabled: false },
    },
  },
  {
    mode: 'modal',
  },
);
```

I had to put `navigationOptions` and `gesturesEnabled` on each screen I added to the modal stack navigator.

**Comment by joshjhargreaves** [comment]
I believe the confusion here stems from the breaking change in the `StackNavigatorConfig` from `navigationOptions` => `defaultNavigationOptions` in `react-navigation 3.x`.

Detailed [here](https://reactnavigation.org/blog/2018/11/01/react-navigation-3.0-rc.html#breaking-changes): 

> Once you get that in place, you may notice that your navigation options aren’t being applied as you expect - this is due to navigationOptions in navigator configuration being renamed to defaultNavigationOptions.

The below works for @david-arteaga because when configuring `navigationOptions` on a per screen basis, the property name is still named `navigationOptions`: 
> I got it working in RN 0.58.1 with react-navigation 3.0.9 on iOS with the following
> I had to put `navigationOptions` and `gesturesEnabled` on each screen I added to the modal stack navigator.

Here is a working snack of where disabling gestures with `defaultNavigationOptions` works for the modal displayed when pressing the info button at the top right: https://snack.expo.io/@joshyhargreaves/full-screen-modal-v3

**Comment by doituyetdep** [comment]
Here a my example and it works fine.
import React from "react";
import { View, Text, Button } from "react-native";
import { createAppContainer } from "react-navigation"; // Version can be specified in package.json
import { createStackNavigator } from "react-navigation-stack";
// Tạo 2 màn hình để di chuyển
class HomeScreen extends React.Component {
  render() {
    return (
      <View style={{ flex: 1, alignItems: "center", justifyContent: "center" }}>
        <Text>Home Screen</Text>
        <Button
          title="Go to Details"
          onPress={() => {
            this.props.navigation.navigate("Details");  //Link Chuyển hướng dẫn màn hình Detail
          }}
        />
      </View>
    );
  }
}
class DetailsScreen extends React.Component {
  render() {
    return (
      <View style={{ flex: 1, alignItems: "center", justifyContent: "center" }}>
        <Text>Details Screen</Text>
        <Button
          title="Go back"
          onPress={() => this.props.navigation.goBack()}
        />
      </View>
    );
  }
}
// Tạo stack navigator chứa 2 màn hình là Home và Details
const AppNavigator = createStackNavigator(
  {
    Home: {
      screen: HomeScreen,
      navigationOptions: () => ({
        title: 'Home',
        headerStyle: {
          backgroundColor: '#f4511e', 
        },
        headerTitleStyle: { flex: 1, textAlign: 'center'},//Căn giữa Title
        //headerTintColor:'#fff',
        headerRight:(
          <Button
            onPress={()=>alert('This is a button')}
            title="Info"
            color="#f4511e"
            />
        )
      })
    },
    Details: {
      screen: DetailsScreen,
      navigationOptions: () => ({
        title: 'Details',
        gesturesEnabled: true,
      })
    }
  },
  {
  // đặt màn hình mặc định xuất hiên là Home
    initialRouteName: "Home",
    mode: 'modal',
    headerMode: 'none',

  }
);
export default createAppContainer(AppNavigator);
